// src/routes/video/+page.svelte
<main class="flex flex-col items-center justify-center h-screen">
  <h1
    class="text-5xl md:text-7xl mb-10 font-bold text-transparent bg-clip-text bg-gradient-to-r from-mauve to-blue leading-tight"
  >
    ✰ Coming soon ✰
  </h1>
  <a
    href="/"
    class="p-4 font-semibold rounded-lg bg-surface0 hover:bg-surface1 transition-colors duration-150 ease-in-out text-2xl"
  >
    Back Home &rarr;
  </a>
</main>

// pages/video.vue
<template>
  <main class="flex flex-col items-center justify-center h-[87vh]">
    <h1 class="text-7xl mb-10 font-bold text-transparent bg-clip-text bg-gradient-to-r from-mauve to-blue leading-tight">
      ✰ Coming soon ✰
    </h1>
    <NuxtLink to="/" class="p-4 font-semibold rounded-lg bg-surface0 hover:bg-surface1 transition-colors duration-150 ease-in-out text-2xl">Back Home &rarr;</NuxtLink>
  </main>
</template>
